AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/migrate/**'
    - 'db/schema.rb'

Layout/EndOfLine:
  Enabled: False

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'config/routes.rb'


Style/Documentation:
  Enabled: false