development:
  adapter: async

test:
  adapter: test

production:
  adapter: async
  # Uncomment below when Redis is set up
  # adapter: redis
  # url: <%= ENV.fetch('REDIS_URL') { 'redis://localhost:6379/1' } %>
  # channel_prefix: tanooki_production
