development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tanooki_development
  pool: 5
  username: root
  password: supersecretpassword

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tanooki_test
  pool: 5
  username: root
  password: supersecretpassword

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tanooki_production
  pool: 5
  username: root
  password: supersecretpassword
