development:
  adapter: mysql2
  database: tanooki_development
  host: localhost
  username: root
  password: mypassword

test:
  adapter: mysql2
  database: tanooki_test
  host: localhost
  username: root
  password: mypassword

production:
  adapter: mysql2
  database: tanooki_production
  host: localhost
  username: root
  password: mypassword
