Звичайний:
  Звичайний: 1.0
  Вогняний: 1.0
  Водяний: 1.0
  Електричний: 1.0
  Трав'яний: 1.0
  Льодовий: 1.0
  Бойовий: 1.0
  Отруйний: 1.0
  Ґрунтовий: 1.0
  Повітряний: 1.0
  Психічний: 1.0
  Комашиний: 1.0
  Скельний: 0.75
  Примарний: 0.5
  Драконячий: 1.0

Вогняний:
  Звичайний: 1.0
  Вогняний: 0.75
  Водяний: 0.75
  Електричний: 1.0
  Трав'яний: 1.25
  Льодовий: 1.25
  Бойовий: 1.0
  Отруйний: 1.0
  Ґрунтовий: 1.0
  Повітряний: 1.0
  Психічний: 1.0
  Комашиний: 1.25
  Скельний: 0.75
  Примарний: 1.0
  Драконячий: 0.75

Водяний:
  Звичайний: 1.0
  Вогняний: 1.25
  Водяний: 0.75
  Електричний: 0.75
  Трав'яний: 1.0
  Льодовий: 1.0
  Бойовий: 1.0
  Отруйний: 1.0
  Ґрунтовий: 1.25
  Повітряний: 1.0
  Психічний: 1.0
  Комашиний: 1.0
  Скельний: 1.25
  Примарний: 1.0
  Драконячий: 0.75

Електричний:
  Звичайний: 1.0
  Вогняний: 1.0
  Водяний: 1.25
  Електричний: 0.75
  Трав'яний: 0.75
  Льодовий: 1.0
  Бойовий: 1.0
  Отруйний: 1.0
  Ґрунтовий: 0.5
  Повітряний: 1.25
  Психічний: 1.0
  Комашиний: 1.0
  Скельний: 1.0
  Примарний: 1.0
  Драконячий: 0.75

Трав'яний:
  Звичайний: 1.0
  Вогняний: 0.75
  Водяний: 1.25
  Електричний: 1.0
  Трав'яний: 0.75
  Льодовий: 1.0
  Бойовий: 1.0
  Отруйний: 0.75
  Ґрунтовий: 1.25
  Повітряний: 0.75
  Психічний: 1.0
  Комашиний: 0.75
  Скельний: 1.25
  Примарний: 1.0
  Драконячий: 0.75

Льодовий:
  Звичайний: 1.0
  Вогняний: 0.75
  Водяний: 0.75
  Електричний: 1.0
  Трав'яний: 1.25
  Льодовий: 0.75
  Бойовий: 1.0
  Отруйний: 1.0
  Ґрунтовий: 1.25
  Повітряний: 1.25
  Психічний: 1.0
  Комашиний: 1.0
  Скельний: 1.0
  Примарний: 1.0
  Драконячий: 1.25

Бойовий:
  Звичайний: 1.25
  Вогняний: 1.0
  Водяний: 1.0
  Електричний: 1.0
  Трав'яний: 1.0
  Льодовий: 1.25
  Бойовий: 1.0
  Отруйний: 0.75
  Ґрунтовий: 1.0
  Повітряний: 0.75
  Психічний: 0.75
  Комашиний: 0.75
  Скельний: 1.25
  Примарний: 0.5
  Драконячий: 1.0

Отруйний:
  Звичайний: 1.0
  Вогняний: 1.0
  Водяний: 1.0
  Електричний: 1.0
  Трав'яний: 1.25
  Льодовий: 1.0
  Бойовий: 1.0
  Отруйний: 0.75
  Ґрунтовий: 0.75
  Повітряний: 1.0
  Психічний: 1.0
  Комашиний: 1.0
  Скельний: 0.75
  Примарний: 0.75
  Драконячий: 1.0

Ґрунтовий:
  Звичайний: 1.0
  Вогняний: 1.25
  Водяний: 1.0
  Електричний: 1.25
  Трав'яний: 0.75
  Льодовий: 1.0
  Бойовий: 1.0
  Отруйний: 1.25
  Ґрунтовий: 1.0
  Повітряний: 0.5
  Психічний: 1.0
  Комашиний: 0.75
  Скельний: 1.25
  Примарний: 1.0
  Драконячий: 1.0

Повітряний:
  Звичайний: 1.0
  Вогняний: 1.0
  Водяний: 1.0
  Електричний: 0.75
  Трав'яний: 1.25
  Льодовий: 1.0
  Бойовий: 1.25
  Отруйний: 1.0
  Ґрунтовий: 1.0
  Повітряний: 1.0
  Психічний: 1.0
  Комашиний: 1.25
  Скельний: 0.75
  Примарний: 1.0
  Драконячий: 1.0

Психічний:
  Звичайний: 1.0
  Вогняний: 1.0
  Водяний: 1.0
  Електричний: 1.0
  Трав'яний: 1.0
  Льодовий: 1.0
  Бойовий: 1.25
  Отруйний: 1.25
  Ґрунтовий: 1.0
  Повітряний: 1.0
  Психічний: 0.75
  Комашиний: 1.0
  Скельний: 1.0
  Примарний: 1.0
  Драконячий: 1.0

Комашиний:
  Звичайний: 1.0
  Вогняний: 0.75
  Водяний: 1.0
  Електричний: 1.0
  Трав'яний: 1.25
  Льодовий: 1.0
  Бойовий: 0.75
  Отруйний: 0.75
  Ґрунтовий: 1.0
  Повітряний: 0.75
  Психічний: 1.25
  Комашиний: 1.0
  Скельний: 1.0
  Примарний: 0.75
  Драконячий: 1.0

Скельний:
  Звичайний: 1.0
  Вогняний: 1.25
  Водяний: 1.0
  Електричний: 1.0
  Трав'яний: 1.0
  Льодовий: 1.25
  Бойовий: 0.75
  Отруйний: 1.0
  Ґрунтовий: 0.75
  Повітряний: 1.25
  Психічний: 1.0
  Комашиний: 1.25
  Скельний: 1.0
  Примарний: 1.0
  Драконячий: 1.0

Примарний:
  Звичайний: 0.5
  Вогняний: 1.0
  Водяний: 1.0
  Електричний: 1.0
  Трав'яний: 1.0
  Льодовий: 1.0
  Бойовий: 1.0
  Отруйний: 1.0
  Ґрунтовий: 1.0
  Повітряний: 1.0
  Психічний: 1.25
  Комашиний: 1.0
  Скельний: 1.0
  Примарний: 1.25
  Драконячий: 1.0

Драконячий:
  Звичайний: 1.0
  Вогняний: 1.0
  Водяний: 1.0
  Електричний: 1.0
  Трав'яний: 1.0
  Льодовий: 1.0
  Бойовий: 1.0
  Отруйний: 1.0
  Ґрунтовий: 1.0
  Повітряний: 1.0
  Психічний: 1.0
  Комашиний: 1.0
  Скельний: 1.0
  Примарний: 1.0
  Драконячий: 1.25
